
author = "Andika Hadi Hutama"
title = "Deep Learning Classification Leveraging Multi-Temporal Historical Maps for Enabling Urban Analysis in The Past"
graduation-year = 2026
graduation-month = "June"
supervisor1 = "Dr.ir. B.M. (Martijn) Meijers"
supervisor2 = "Prof.dr. A.R. (Ana) Pereira Roders"
coreader    = "TBC"
#graduation-group = "3D geoinformation group"
graduation-group = "Geo-Database Management Centre"

